image: docker:19.03.0

stages:
  - build
  - test
  - release
  - trigger

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_REGISTRY: docker-registry.kronova.net
  DOCKER_TLS_CERTDIR: ""
  CONTAINER_TEST: docker-registry.kronova.net/docker/typo3-php:$CI_COMMIT_BRANCH
  CONTAINER_DOCKERHUB_BRANCH: kronova/typo3-php:$CI_COMMIT_BRANCH
  CONTAINER_DOCKERHUB_LATEST: kronova/typo3-php:latest
  CONTAINER_DOCKERHUB_TAG: kronova/typo3-php:$CI_COMMIT_TAG

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ./.build

services:
  - docker:19.03.0-dind

before_script:
  - echo "$CI_BUILD_TOKEN" | docker login --username gitlab-ci-token $DOCKER_REGISTRY --password-stdin

build:
  stage: build
  script:
    - docker build -t $CONTAINER_TEST .
    # todo: remove the gitlab container registry completely and use docker hub only
    - docker push $CONTAINER_TEST
    - mkdir -p ./.build
    - docker save $CONTAINER_TEST -o ./.build/image.tar
  only:
    - master
    - /^php-.*$/

.test:
  stage: test
  before_script:
    # use gitlab-ci cache instead of container registry to bypass the slow pull
    - docker load < ./.build/image.tar || true
  only:
    - master
    - /^php-.*$/

test-php:
  extends: .test
  script:
    - docker load < ./.build/image.tar || true
    - docker run $CONTAINER_TEST php -v

test-typo3_8:
  extends: .test
  script:
    - docker run $CONTAINER_TEST composer require typo3/minimal '^8'

test-typo3_9:
  extends: .test
  script:
    - docker run $CONTAINER_TEST composer require typo3/minimal '^9'

test-imagemagick:
  extends: .test
  script:
    - docker run $CONTAINER_TEST convert -version

push-on-dockerhub:
  stage: release
  before_script: []
  script:
    - docker pull $CONTAINER_TEST
    - docker tag $CONTAINER_TEST $CONTAINER_DOCKERHUB_LATEST
    - docker logout
    - echo "$REGISTRY_PASSWORD" | docker login --username "$REGISTRY_USER" --password-stdin
    - docker push $CONTAINER_DOCKERHUB_LATEST
  only:
    - master
  allow_failure: false
  when: manual

push-tag-on-dockerhub:
  stage: release
  before_script: []
  script:
    - docker pull $CONTAINER_TEST
    - docker tag $CONTAINER_TEST $CONTAINER_DOCKERHUB_TAG
    - docker logout
    - echo "$REGISTRY_PASSWORD" | docker login --username "$REGISTRY_USER" --password-stdin
    - docker push $CONTAINER_DOCKERHUB_TAG
  only:
    - tags

push-branch-on-dockerhub:
  stage: release
  before_script: []
  script:
    - docker pull $CONTAINER_TEST
    - docker tag $CONTAINER_TEST $CONTAINER_DOCKERHUB_BRANCH
    - docker logout
    - echo "$REGISTRY_PASSWORD" | docker login --username "$REGISTRY_USER" --password-stdin
    - docker push $CONTAINER_DOCKERHUB_BRANCH
  only:
    - /^php-.*$/
  except:
    - tags

trigger-typo3-utilities:
  image: kronova/typo3-utilities
  stage: trigger
  before_script:
    - ''
  script:
    - "curl -X POST -F token=d5403e897bd63d9d2213f6febe3921 -F ref=master https://git.kronova.net/api/v4/projects/42/trigger/pipeline"
  only:
    - master